# Generated by Django 5.0.6 on 2024-05-22 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_is_active_product_is_visible'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
